name: Build and Release App
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Configure CMake
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release

      - name: Package Files into a Clean Folder
        shell: bash
        run: |
          FOLDER_NAME="AsciiArt-${{ matrix.os }}"
          mkdir -p $FOLDER_NAME/fonts
          
          cp -r build/fonts/* $FOLDER_NAME/fonts/ 2>/dev/null || true
          
          cp build/AsciiArt $FOLDER_NAME/ 2>/dev/null || true
          cp build/Release/AsciiArt.exe $FOLDER_NAME/ 2>/dev/null || true
          
          cmake -E tar cfv $FOLDER_NAME.zip --format=zip $FOLDER_NAME/

      - name: Upload Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: package-${{ matrix.os }}
          path: AsciiArt-${{ matrix.os }}.zip

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download all Artifacts
        uses: actions/download-artifact@v8
        with:
          path: artifacts

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v3
        with:
          files: artifacts/**/*.zip
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}