name: Build and Release App
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure CMake
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: AsciiArt-${{ matrix.os }}
          path: |
            build/AsciiArt
            build/Release/AsciiArt.exe
            build/fonts/
          if-no-files-found: ignore